sudo: false
language: c
cache:
  directories:
    - $HOME/arch-linux
    - $HOME/arch-linux-pkg
addons:
  apt:
    packages:
      - expect
      - qemu-system
      - sshpass
script:
  - "./ci/build-packages-in-guest"
