dist: trusty
sudo: false
language: c
cache:
  directories:
    - $HOME/arch-linux
    - $HOME/arch-linux-pkg
addons:
  apt:
    packages:
      - sshpass
      - qemu-kvm
script:
  - "./ci/build-packages-in-guest"
