#!/bin/bash -u

set -o pipefail


cd "$(dirname -- $0)/.."

ec=0

for pkgbuild in $(find . -type f -name PKGBUILD)
do
  pushd $(dirname $pkgbuild) > /dev/null

  makepkg -f ./PKGBUILD
  rc=$?

  echo '=============================================='
  echo -n "$(basename $PWD): "

  if [ $rc -eq 0 ]
  then
    echo OK
  else
    echo KO
    ec=$(( $ec + 1 ))
  fi

  echo -e '==============================================\n'

  popd > /dev/null
done

exit $ec
